package sxkeji.net.dailydiary;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import java.io.Serializable;
// KEEP INCLUDES END
/**
 * Entity mapped to table ARTICLE.
 */
public class Article implements Serializable{

    private Long id;
    /** Not-null value. */
    private String date;
    private String address;
    private String weather;
    /** Not-null value. */
    private String title;
    /** Not-null value. */
    private String content;
    private Integer type;
    private String img_path;
    private String objectId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Article() {
    }

    public Article(Long id) {
        this.id = id;
    }

    public Article(Long id, String date, String address, String weather, String title, String content, Integer type, String img_path, String objectId) {
        this.id = id;
        this.date = date;
        this.address = address;
        this.weather = weather;
        this.title = title;
        this.content = content;
        this.type = type;
        this.img_path = img_path;
        this.objectId = objectId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getWeather() {
        return weather;
    }

    public void setWeather(String weather) {
        this.weather = weather;
    }

    /** Not-null value. */
    public String getTitle() {
        return title;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTitle(String title) {
        this.title = title;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public Integer getType() {
        return type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getImg_path() {
        return img_path;
    }

    public void setImg_path(String img_path) {
        this.img_path = img_path;
    }

    public String getObjectId() {
        return objectId;
    }

    public void setObjectId(String objectId) {
        this.objectId = objectId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
