package sxkeji.net.dailydiary;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import sxkeji.net.dailydiary.Article;
import sxkeji.net.dailydiary.Todo;

import sxkeji.net.dailydiary.ArticleDao;
import sxkeji.net.dailydiary.TodoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig articleDaoConfig;
    private final DaoConfig todoDaoConfig;

    private final ArticleDao articleDao;
    private final TodoDao todoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        todoDaoConfig = daoConfigMap.get(TodoDao.class).clone();
        todoDaoConfig.initIdentityScope(type);

        articleDao = new ArticleDao(articleDaoConfig, this);
        todoDao = new TodoDao(todoDaoConfig, this);

        registerDao(Article.class, articleDao);
        registerDao(Todo.class, todoDao);
    }
    
    public void clear() {
        articleDaoConfig.getIdentityScope().clear();
        todoDaoConfig.getIdentityScope().clear();
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public TodoDao getTodoDao() {
        return todoDao;
    }

}
