package sxkeji.net.dailydiary;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TODO.
 */
public class Todo {

    private Long id;
    private java.util.Date date;
    /** Not-null value. */
    private String content;
    private int color;
    private boolean hasReminder;
    private Boolean showOnLockScreen;

    public Todo() {
    }

    public Todo(Long id) {
        this.id = id;
    }

    public Todo(Long id, java.util.Date date, String content, int color, boolean hasReminder, Boolean showOnLockScreen) {
        this.id = id;
        this.date = date;
        this.content = content;
        this.color = color;
        this.hasReminder = hasReminder;
        this.showOnLockScreen = showOnLockScreen;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getDate() {
        return date;
    }

    public void setDate(java.util.Date date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getContent() {
        return content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setContent(String content) {
        this.content = content;
    }

    public int getColor() {
        return color;
    }

    public void setColor(int color) {
        this.color = color;
    }

    public boolean getHasReminder() {
        return hasReminder;
    }

    public void setHasReminder(boolean hasReminder) {
        this.hasReminder = hasReminder;
    }

    public Boolean getShowOnLockScreen() {
        return showOnLockScreen;
    }

    public void setShowOnLockScreen(Boolean showOnLockScreen) {
        this.showOnLockScreen = showOnLockScreen;
    }

}
